# site settings
title: Juuso Laine
subtitle: Portfolio
email: contact@jusola.xyz
baseurl: ""
url: https://jusola.xyz
author: Juuso Laine

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4
featured-count: 3

# social settings
500px_url:
facebook_url:
github_url: https://github.com/jusola
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/juulain

collections:
  projects:
    output: true
  pages:
    output: true
  photos:
    output: true

excerpt_separator: <!--more-->
    
# build settings
markdown: kramdown

sass:
  style: compressed
