# site settings
title: Juuso Laine
subtitle: Portfolio
email: contact@juusolain.fi
baseurl: ""
url: https://juusolain.fi
author: Juuso Laine

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4
featured-count: 3

# social settings
500px_url:
facebook_url:
github_url: https://github.com/juusolain
googleplus_url:
instagram_url: https://instagram.com/juusolain
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

collections:
  programming:
    output: true
  eventtech:
    output: true
  pages:
    output: true

excerpt_separator: <!--more-->

# build settings
markdown: kramdown

sass:
  style: compressed
